from pathlib import Path

# Configuration Constants
MSA_QUERY_HOST_URL = "https://api.colabfold.com"

OUTPUT_DIRS = {
    "a3m": Path("a3m/"),
    "folded": Path("folded/"),
    "fastas": Path("fastas/"),
    "metrics_db": Path("metrics/metrics_db.json"),
    "msa_results": Path("msa_results/")
}

LOGGING_CONFIG = {
    "level": "INFO",
    "format": "%(asctime)s - %(levelname)s - %(message)s"
}

# Directory Paths
DATA_DIR = Path(__file__).parent.parent / "data"
FOLD_RESULTS_DIR = DATA_DIR / "fold_results"
PEPMLM_RESULTS_DIR = DATA_DIR / "pepmlm_results"
EVO_PROT_GRAD_RESULTS_DIR = DATA_DIR / "evo_prot_grad_results"

# Example Sequences
EGFS = 'NSYPGCPSSYDGYCLNGGVCMHIESLDSYTCNCVIGYSGDRCQTRDLRWWELR'
EGFR = ('LEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVA'
        'GYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEILHGAVRF'
        'SNNPALCNVESIQWRDIVSSDFLSNMSMDFQNHLGSCQKCDPSCPNGSCWGAGEENCQKLTKIIC'
        'AQQCSGRCRGKSPSDCCHNQCAAGCTGPRESDCLVCRKFRDEATCKDTCPPLMLYNPTTYQMDVN'
        'PEGKYSFGATCVKKCPRNYVVTDHGSCVRACGADSYEMEEDGVRKCKKCEGPCRKVCNGIGIGEF'
        'KDSLSINATNIKHFKNCTSISGDLHILPVAFRGDSFTHTPPLDPQELDILKTVKEITGFLLIQAW'
        'PENRTDLHAFENLEIIRGRTKQHGQFSLAVVSLNITSLGLRSLKEISDGDVIISGNKNLCYANTI'
        'NWKKLFGTSGQKTKIISNRGENSCKATGQVCHALCSPEGCWGPEPRDCVSCRNVSRGRECVDKCKL'
        'LEGEPREFVENSECIQCHPECLPQAMNITCTGRGPDNCIQCAHYIDGPHCVKTCPAGVMGENNTL'
        'VWKYADAGHVCHLCHPNCTYGCTGPGLRGCPTNGHHHHHH')

COLABFOLD_GPU_CONCURRENCY_LIMIT = 80

# Volume Name
MODAL_VOLUME_NAME = "egfr_binders"